@echo off
REM ---------------------------------------------------------------------------
REM Gradle start up script for Windows
REM ---------------------------------------------------------------------------

REM (The real gradlew.bat needs generated by Gradle or copied from a working Android Studio project)
REM For placeholder purposes:
echo This is a placeholder for Windows gradlew.bat
