name: Deploy React App to Netlify

on:
  push:
    branches:
      - main
    paths:
      - 'test-app*/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Detect changed app folder
        id: detect
        run: |
          CHANGED_DIR=$(git diff --name-only HEAD~1 HEAD | grep -o 'test-app[^/]*' | sort -u | head -n 1)
          echo "changed_folder=$CHANGED_DIR" >> $GITHUB_OUTPUT
          echo "Detected folder: $CHANGED_DIR"

      - name: Install dependencies
        run: |
          cd ${{ steps.detect.outputs.changed_folder }}
          npm install

      - name: Build project
        run: |
          cd ${{ steps.detect.outputs.changed_folder }}
          npm run build

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          cd ${{ steps.detect.outputs.changed_folder }}
          netlify deploy \
            --dir=build \
            --prod \
            --auth=$NETLIFY_AUTH_TOKEN \
            --site=$(netlify sites:create --name "${{ steps.detect.outputs.changed_folder }}-$(date +%s)" --json | jq -r '.site_id')
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
